name: mapd-b
channels:
  - conda-forge
dependencies:
  - python=3.13
  - dask=2025.11.0
  - distributed=2025.11.0
  - scikit-learn=1.7.2
  - numpy=2.3.5
  - pandas=2.3.3
  - pyarrow=21.0.0
  - matplotlib=3.10.6
  - jupyterlab
